#!/usr/bin/env node
// Generates derived files from the canonical sources in skills/ and adapters/_core.md.
// Outputs: skills/god-styles/references/00-index.md, catalog.json, dist/GOD-OF-DESIGN.md,
//          dist/GOD-OF-DESIGN-LITE.md, llms.txt, adapters/<tool>/*
// Usage: node scripts/build.mjs [--check]   (--check fails if generated files are out of date)
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, statSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const VERSION = pkg.version;
const REPO = "https://github.com/cumabozkurt/god-of-design";
const outputs = new Map();
const emit = (rel, content) => outputs.set(rel, content.replace(/\r\n/g, "\n"));

export function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) return { data: null, body: text };
  const data = {};
  let parent = null;
  for (const line of m[1].split("\n")) {
    const top = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    const nested = line.match(/^\s{2,}([A-Za-z0-9_-]+):\s*(.*)$/);
    if (top) { const v = top[2].trim(); if (v === "") { data[top[1]] = {}; parent = top[1]; } else { data[top[1]] = v.replace(/^"(.*)"$/, "$1"); parent = null; } }
    else if (nested && parent) data[parent][nested[1]] = nested[2].trim().replace(/^"(.*)"$/, "$1");
  }
  return { data, body: text.slice(m[0].length) };
}

// ---------- skills ----------
const SKILL_ORDER = ["god-of-design", "god-styles", "god-color", "god-typography", "god-layout", "god-ui-ux", "god-mobile",
  "god-tokens", "god-accessibility", "god-social-media", "god-print", "god-branding", "god-presentations", "god-motion",
  "god-dataviz", "god-imagegen", "god-anti-slop", "god-review", "god-output"];
const skillDirs = readdirSync(join(ROOT, "skills")).filter((d) => existsSync(join(ROOT, "skills", d, "SKILL.md")));
const extra = skillDirs.filter((d) => !SKILL_ORDER.includes(d)).sort();
const skills = [...SKILL_ORDER.filter((d) => skillDirs.includes(d)), ...extra].map((dir) => {
  const { data, body } = parseFrontmatter(readFileSync(join(ROOT, "skills", dir, "SKILL.md"), "utf8"));
  const refDir = join(ROOT, "skills", dir, "references");
  const refs = existsSync(refDir) ? readdirSync(refDir).filter((f) => f.endsWith(".md")).sort() : [];
  return { dir, name: data.name, description: data.description, body, refs };
});

// ---------- styles ----------
const STYLE_FILES = [
  ["01-art-movements.md", "Art & design movements"],
  ["02-digital-ui.md", "Digital & UI styles"],
  ["03-retro-subcultures.md", "Retro, internet & subculture"],
  ["04-world-traditions.md", "World traditions"],
];
const styles = [];
for (const [file, family] of STYLE_FILES) {
  const text = readFileSync(join(ROOT, "skills/god-styles/references", file), "utf8");
  let region = null;
  for (const block of text.split(/\n(?=## |### )/)) {
    if (block.startsWith("## ")) { region = block.split("\n")[0].slice(3).trim(); continue; }
    if (!block.startsWith("### ")) continue;
    const name = block.split("\n")[0].slice(4).trim();
    const id = (block.match(/\*\*ID:\*\*\s*`([^`]+)`/) || [])[1];
    const origin = ((block.match(/\*\*Origin:\*\*\s*(.+)/) || [])[1] || "").replace(/\s+/g, " ");
    styles.push({ id, name, family, region: region && !/protocol|^Respect/i.test(region) ? region : null, file, origin });
  }
}

let index = `# Style Index (${styles.length} styles)\n\n> Generated by \`scripts/build.mjs\`. Do not edit by hand.\n\nUse the ID with the \`god-style\` command or say "in the style of <name>". Open the linked file for the full entry.\n`;
for (const [file, family] of STYLE_FILES) {
  const list = styles.filter((s) => s.file === file);
  index += `\n## ${family} (${list.length}) · [${file}](${file})\n\n| ID | Style | Origin |\n|---|---|---|\n`;
  for (const s of list) index += `| \`${s.id}\` | ${s.name}${s.region ? ` · _${s.region}_` : ""} | ${s.origin.split(/[.;]/)[0].slice(0, 90)} |\n`;
}
emit("skills/god-styles/references/00-index.md", index);

// ---------- tools ----------
const tools = [
  { id: "claude", name: "Claude Code", global: "~/.claude/skills + ~/.claude/commands", project: ".claude/skills + .claude/commands", native: "Skills, slash commands, plugin marketplace" },
  { id: "codex", name: "OpenAI Codex CLI", global: "~/.agents/skills + block in ~/.codex/AGENTS.md", project: ".agents/skills + block in AGENTS.md", native: "Skills ($god-of-design), AGENTS.md" },
  { id: "opencode", name: "OpenCode", global: "~/.config/opencode/skills + commands", project: ".opencode/skills + .opencode/commands", native: "Skills, commands (also reads .claude/.agents skills)" },
  { id: "antigravity", name: "Google Antigravity", global: "~/.gemini/config/skills", project: ".agents/skills + .agents/rules/god-of-design.md", native: "Agent Skills, rules" },
  { id: "gemini", name: "Gemini CLI", global: "~/.gemini/skills", project: ".gemini/skills", native: "Agent Skills (also reads ~/.agents/skills)" },
  { id: "cursor", name: "Cursor", global: "~/.cursor/skills", project: ".cursor/skills + .cursor/rules/god-of-design.mdc", native: "Agent Skills, project rules" },
  { id: "copilot", name: "GitHub Copilot (VS Code / CLI)", global: "~/.copilot/skills", project: ".github/skills + .github/instructions/god-of-design.instructions.md", native: "Agent Skills, custom instructions" },
  { id: "windsurf", name: "Windsurf", global: "block in ~/.codeium/windsurf/memories/global_rules.md + bundle", project: ".windsurf/rules/god-of-design.md + bundle", native: "Rules (≤ 6,000 chars) + reference bundle" },
  { id: "cline", name: "Cline", global: "~/Documents/Cline/Rules/god-of-design.md + bundle", project: ".clinerules/god-of-design.md + bundle", native: "Rules + reference bundle" },
];

emit("catalog.json", JSON.stringify({
  name: "god-of-design", version: VERSION, homepage: REPO,
  counts: { skills: skills.length, styles: styles.length, commands: readdirSync(join(ROOT, "commands")).filter((f) => f.endsWith(".md")).length, tools: tools.length },
  skills: skills.map(({ name, description }) => ({ name, description })),
  styles: styles.map(({ id, name, family, region }) => ({ id, name, family, ...(region ? { region } : {}) })),
  tools,
}, null, 2) + "\n");

// ---------- bundles ----------
const core = readFileSync(join(ROOT, "adapters/_core.md"), "utf8").trim();
const strip = (t) => t.replace(/^# .*\n+/, "");
let full = `# GOD OF DESIGN: complete reference (v${VERSION})\n\n> Single-file edition of every skill and reference in ${REPO}. Generated by \`scripts/build.mjs\`. Paste or upload it into any LLM (ChatGPT, Gemini, Claude.ai, Mistral, local models) as a knowledge file or system prompt.\n\n## Contents\n\n`;
full += skills.map((s, i) => `${i + 1}. [${s.name}](#skill-${s.name})`).join("\n") + "\n\n---\n\n" + core + "\n";
for (const s of skills) {
  full += `\n---\n\n<a id="skill-${s.name}"></a>\n# Skill: ${s.name}\n\n> ${s.description}\n\n${strip(s.body).trim()}\n`;
  for (const r of s.refs) {
    const t = readFileSync(join(ROOT, "skills", s.dir, "references", r), "utf8");
    full += `\n## ${s.name} › ${r}\n\n${t.replace(/^#{1,6} /gm, (h) => "#" + h).trim()}\n`;
  }
}
// In the single-file bundle, relative links cannot resolve: turn them into plain text.
full = full.replace(/\[([^\]]+)\]\((?!https?:|#|mailto:)([^)\s]+)\)/g, "$1");
emit("dist/GOD-OF-DESIGN.md", full);

const pick = (dir) => strip(skills.find((s) => s.dir === dir).body).trim();
let lite = `# GOD OF DESIGN: lite system prompt (v${VERSION})\n\n> Compact edition for custom instructions / system prompts. Full edition: dist/GOD-OF-DESIGN.md · ${REPO}\n\n${core}\n\n---\n\n## Anti-slop gate\n\n${pick("god-anti-slop").split("## The slop gate")[1] ? "## The slop gate" + pick("god-anti-slop").split("## The slop gate")[1] : ""}\n\n---\n\n## Style IDs (${styles.length})\n\n`;
for (const [file, family] of STYLE_FILES) lite += `**${family}:** ` + styles.filter((s) => s.file === file).map((s) => `${s.name} (\`${s.id}\`)`).join(", ") + "\n\n";
emit("dist/GOD-OF-DESIGN-LITE.md", lite);

let llms = `# God of Design\n\n> Cross-tool design-intelligence pack for AI agents: ${skills.length} skills, ${styles.length} styles (art movements, digital UI, retro, world traditions), every design area (web/UI/UX, mobile, social media, print, branding, presentations, motion, data viz, image generation). MIT.\n\n## Docs\n- [README](${REPO}#readme)\n- [Full single-file reference](${REPO}/blob/main/dist/GOD-OF-DESIGN.md)\n- [Lite system prompt](${REPO}/blob/main/dist/GOD-OF-DESIGN-LITE.md)\n- [Style index](${REPO}/blob/main/skills/god-styles/references/00-index.md)\n\n## Skills\n`;
for (const s of skills) llms += `- [${s.name}](${REPO}/blob/main/skills/${s.dir}/SKILL.md): ${s.description}\n`;
emit("llms.txt", llms);

// ---------- adapters ----------
const coreBody = core.replace(/^# .*\n+/, "");
const H = "God of Design";
const desc = "God of Design: design workflow, 100+ styles, anti-slop rules and routing for any visual design task (web, mobile, social, print, branding, slides, motion, data viz, image prompts).";
emit("adapters/cursor/god-of-design.mdc", `---\ndescription: ${desc}\nglobs:\nalwaysApply: false\n---\n# ${H}\n\n${coreBody}\n`);
emit("adapters/windsurf/god-of-design.md", `---\ntrigger: model_decision\ndescription: ${desc}\n---\n# ${H}\n\n${coreBody}\n`);
emit("adapters/antigravity/god-of-design.md", `---\ntrigger: model_decision\ndescription: ${desc}\n---\n# ${H}\n\n${coreBody}\n`);
emit("adapters/cline/god-of-design.md", `# ${H}\n\n${coreBody}\n`);
emit("adapters/copilot/god-of-design.instructions.md", `---\napplyTo: "**"\ndescription: ${desc}\n---\n# ${H}\n\n${coreBody}\n`);
emit("adapters/codex/AGENTS.snippet.md", `## ${H} (design skills)\n\nFor any visual design task (web/UI, app screens, social posts, posters, logos, slides, motion, charts, image prompts), use the installed \`god-of-design\` skill first (\`$god-of-design\`). It routes to \`god-styles\`, \`god-color\`, \`god-typography\`, \`god-ui-ux\`, \`god-social-media\`, \`god-print\`, \`god-branding\`, \`god-presentations\`, \`god-anti-slop\`, \`god-review\` and others. Always: brief → one named direction → tokens → build → anti-slop and review gate. WCAG 2.2 AA, exact values, no AI slop, respectful use of cultural styles.\n`);
emit("adapters/gemini/GEMINI.snippet.md", outputs.get("adapters/codex/AGENTS.snippet.md").replace("(`$god-of-design`)", "(activate it with `/skills` or by asking for a design task)"));
emit("adapters/generic/SYSTEM-PROMPT.md", lite);

// ---------- write / check ----------
let stale = [];
for (const [rel, content] of outputs) {
  const abs = join(ROOT, rel);
  const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  if (current === content) continue;
  if (CHECK) { stale.push(rel); continue; }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}
if (CHECK && stale.length) {
  console.error(`Generated files are out of date. Run: node scripts/build.mjs\n  ${stale.join("\n  ")}`);
  process.exit(1);
}
const windsurfLen = outputs.get("adapters/windsurf/god-of-design.md").length;
console.log(`${CHECK ? "Checked" : "Built"}: ${skills.length} skills, ${styles.length} styles, ${tools.length} tools · bundle ${(full.length / 1024).toFixed(0)} KB · lite ${(lite.length / 1024).toFixed(0)} KB · windsurf rule ${windsurfLen} chars`);
