// Builds docs/images/banner.svg from docs/images/banner.src.svg by turning every <text> into
// outlined <path>s, so the banner looks identical everywhere: GitHub shows README SVGs as
// images, which cannot load web fonts, and fallback fonts (e.g. DejaVu on Linux) are wider
// and made the title run into the tiles.
//   npm i --no-save opentype.js && node scripts/outline-banner.mjs
// Each <text> in the source must carry: x, y, font-size, data-font (serif-700 | sans-400 | sans-700),
// and optionally letter-spacing and fill.  Fonts (OFL): Gelasio (Georgia metrics), Inter.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "docs/images/banner.src.svg");
const OUT = path.join(ROOT, "docs/images/banner.svg");
const FONTS = {
  "serif-700": "https://fonts.gstatic.com/s/gelasio/v14/cIfiMaFfvUQxTTqS3iKJkLGbI41wQL_vkCcs.ttf",
  "sans-400": "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfMZg.ttf",
  "sans-700": "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuFuYMZg.ttf",
};
const fonts = {};
for (const [k, url] of Object.entries(FONTS)) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`font download failed (${res.status}): ${url}`);
  fonts[k] = opentype.parse(await res.arrayBuffer());
}
const attr = (s, n) => (s.match(new RegExp(`\\s${n}="([^"]*)"`)) || [])[1];
const decode = (t) => t.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"');

let svg = fs.readFileSync(SRC, "utf8");
let count = 0;
const widths = [];
svg = svg.replace(/<text\b([^>]*)>([\s\S]*?)<\/text>/g, (_, attrs, raw) => {
  const font = fonts[attr(attrs, "data-font")];
  if (!font) throw new Error(`<text> needs data-font: ${attrs}`);
  const x0 = Number(attr(attrs, "x")), y = Number(attr(attrs, "y"));
  const tracking = Number(attr(attrs, "letter-spacing") || 0), fill = attr(attrs, "fill");
  const maxWidth = Number(attr(attrs, "data-max-width") || Infinity);
  const text = decode(raw.trim());
  const glyphs = [...text].map((ch) => font.charToGlyph(ch));
  const widthAt = (sz) => glyphs.reduce((w, g, i) => w + g.advanceWidth * sz / font.unitsPerEm + (i < glyphs.length - 1 ? tracking + (font.getKerningValue(g, glyphs[i + 1]) * sz) / font.unitsPerEm : 0), 0);
  let size = Number(attr(attrs, "font-size"));
  while (widthAt(size) > maxWidth) size -= 0.5;   // shrink to fit instead of running into the artwork
  const scale = size / font.unitsPerEm;
  widths.push([text, size, Math.round(x0 + widthAt(size))]);
  let x = x0, d = "";
  glyphs.forEach((g, i) => {
    if (g.index === 0) throw new Error(`missing glyph #${i} in ${text}`);
    d += g.getPath(x, y, size).toPathData(1);
    x += g.advanceWidth * scale + tracking;
    if (glyphs[i + 1]) x += font.getKerningValue(g, glyphs[i + 1]) * scale;
  });
  count++;
  return `<path${fill ? ` fill="${fill}"` : ""} d="${d}"/>`;
});
svg = svg.replace(/<!-- SOURCE:[\s\S]*?-->/, "<!-- Generated by scripts/outline-banner.mjs from banner.src.svg: edit the source, not this file. -->");
fs.writeFileSync(OUT, svg);
for (const [t, sz, right] of widths) console.log(`  ${String(right).padStart(4)}px right edge  ${sz}px  ${t}`);
console.log(`wrote ${path.relative(ROOT, OUT)}: ${count} text runs outlined, ${(svg.length / 1024).toFixed(1)} KB`);
